name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Set up Deps
      run: apt update && apt install -y libudev-dev
    
    - name: Run tests
      run: go test -v ./...
