name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    
    - name: Install dependencies
      run: DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y fuse-overlayfs
    
    - name: Run tests
      run: go test -v ./...
