name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      run: apt update && apt install -y libudev-dev golang-go
    
    - name: Run tests
      run: go test -v ./...
